---
- name: Update package cache
  package_facts:
    manager: auto

- name: Install common packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - wget
    - unzip
    - git
    - htop

- name: Ensure timezone is set correctly
  timezone:
    name: UTC

- name: Update all packages to latest
  package:
    name: "*"
    state: latest
  when: ansible_os_family == "RedHat"