---
- name: Synchronize /etc/hosts across all servers
  hosts: all
  become: true
  
  tasks:
    - name: Deploy unified hosts file
      ansible.builtin.template:
        src: hosts.j2
        dest: /etc/hosts
        backup: yes
        owner: root
        group: root
        mode: '0644'