---
- name: Synchronize /etc/hosts across all servers
  hosts: all
  become: true
  vars_files:
    - ../inventory/group_vars/all.yml

  tasks:
    - name: Debug variables
      debug:
	msg: "server_ips={{ server_ips | default('UNDEFINED') }}"

    - name: Deploy unified hosts file
      ansible.builtin.template:
        src: hosts.j2
        dest: /etc/hosts
        backup: yes
        owner: root
        group: root
        mode: '0644'
