---
- name: Synchronize /etc/hosts across all servers
  hosts: all
  become: yes
  
  vars_files:
    - ../inventory/group_vars/all.yml

  tasks:
    - name: Deploy unified hosts file
      ansible.builtin.template:
        src: ../templates/hosts.j2 
        dest: /etc/hosts
        backup: yes
        owner: root
        group: root
        mode: '0644'
      notify: Hosts File Synced # Triggers the handler below

    - name: Debug hosts_entries variable content (Verification Step)
      ansible.builtin.debug:
        msg: "hosts_entries: {{ hosts_entries }}"

  handlers:
    - name: Hosts File Synced
      ansible.builtin.debug:
        msg: "Successfully updated /etc/hosts on {{ inventory_hostname }}"
