---
- name: Install Nginx
  package:
    name: nginx
    state: present

- name: Deploy Nginx configuration
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/conf.d/{{ app_name }}.conf"
  notify: restart nginx

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes

- name: Open firewall port for HTTP
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
    immediate: yes
  when: ansible_os_family == "RedHat"